language: ruby
language: perl
os: osx
osx_image: xcode9.4
rvm: system

before_install:
  - brew update || brew update
  - export HOMEBREW_DEVELOPER="1"
  - tools/all-fixes.sh
install:
  - brew tap KDE-mac/kde file://$PWD
script:
  # - CHANGED_FILES=`git diff --name-only $TRAVIS_COMMIT_RANGE`
  # - echo $CHANGED_FILES
  # - tools/travis-ci.sh $CHANGED_FILES
  - tools/install.sh
